// ============================================
// Scene Graph — Stage 5 Output
// Generated by Scene Director Agent
// Consumed by the 3D rendering engine
// ============================================

export interface SceneGraph {
  scene_id: string;
  script_scene_ref: string;

  environment: EnvironmentConfig;
  layout: LayoutConfig;
  structures: Structure[];
  npcs: NPCInstance[];
  interactive_objects: InteractiveObject[];
  triggers: SceneTrigger[];
  cinematic_sequences: CinematicSequence[];
}

// ---- Environment ----

export interface EnvironmentConfig {
  skybox: {
    type: "preset" | "ai_generated" | "color";
    value: string; // preset name, prompt, or hex color
    time_of_day: "dawn" | "morning" | "noon" | "afternoon" | "dusk" | "night";
  };
  terrain: {
    type: "flat" | "heightmap" | "water";
    material: string;
    size: [number, number];
    color?: string;
  };
  lighting: {
    sun: {
      direction: [number, number, number];
      color: string;
      intensity: number;
      castShadow: boolean;
    };
    ambient: {
      color: string;
      intensity: number;
    };
    point_lights?: {
      position: [number, number, number];
      color: string;
      intensity: number;
      distance?: number;
    }[];
  };
  fog?: {
    color: string;
    near: number;
    far: number;
  };
  particles?: {
    type: "dust" | "snow" | "rain" | "fireflies" | "petals" | "smoke";
    density: "low" | "medium" | "high";
    area?: [number, number, number];
  }[];
  audio: {
    ambient?: string;
    music?: string;
    volume?: number;
  };
}

// ---- Layout ----

export interface LayoutConfig {
  player_spawn: {
    position: [number, number, number];
    look_at: [number, number, number];
  };
  boundaries: {
    type: "soft_wall" | "hard_wall" | "none";
    shape: "rectangle" | "circle";
    size: [number, number];
    message_on_hit?: string;
  };
}

// ---- Structures (buildings, terrain features) ----

export interface Structure {
  id: string;
  type: "building" | "landmark" | "decoration" | "terrain_feature";
  asset_id?: string; // references asset registry
  model_url?: string; // URL to GLB/GLTF model (takes priority over primitive)
  primitive?: "box" | "cylinder" | "sphere" | "cone"; // fallback if no model
  position: [number, number, number];
  rotation: [number, number, number];
  scale: [number, number, number];
  material?: {
    color?: string;
    metalness?: number;
    roughness?: number;
    opacity?: number;
    texture?: string;
  };
  label?: string;
  interactive: boolean;
  children?: Structure[]; // nested objects (e.g. props on a table)
}

// ---- NPCs ----

export interface NPCInstance {
  id: string;
  character_ref: string; // references Script.characters[].id
  name: string;
  avatar: {
    model: string; // asset ID or preset
    model_url?: string; // URL to GLB/GLTF character model
    clothing?: string;
    accessories?: string[];
    scale?: number;
  };
  position: [number, number, number];
  rotation: [number, number, number];
  behavior: {
    idle_animation: string;
    greeting_animation?: string;
    dialogue_enabled: boolean;
    dialogue_mode: "ai_realtime" | "scripted";
    patrol_path?: [number, number, number][];
    interaction_radius: number;
  };
  // Visual indicators
  indicator?: {
    type: "exclamation" | "question" | "speech" | "none";
    color?: string;
  };
}

// ---- Interactive Objects ----

export interface InteractiveObject {
  id: string;
  name: string;
  asset_id?: string;
  model_url?: string; // URL to GLB/GLTF model
  primitive?: "box" | "cylinder" | "sphere";
  position: [number, number, number];
  rotation: [number, number, number];
  scale: [number, number, number];
  material?: {
    color?: string;
    emissive?: string;
    emissiveIntensity?: number;
  };
  interaction: {
    type: "examine" | "pickup" | "activate" | "choice_trigger";
    highlight_on_hover: boolean;
    cursor?: string;
    script_interaction_ref?: string; // links to Script interaction ID
    on_interact: InteractAction;
  };
}

export type InteractAction =
  | { type: "show_panel"; title: string; description: string; image?: string }
  | { type: "trigger_dialogue"; npc_id: string; dialogue_id?: string }
  | { type: "trigger_choice"; choice_interaction_ref: string }
  | { type: "collect_item"; item_id: string; item_name: string }
  | { type: "trigger_cinematic"; cinematic_id: string }
  | { type: "unlock_area"; area_id: string };

// ---- Triggers ----

export interface SceneTrigger {
  id: string;
  type: "proximity" | "item_collected" | "dialogue_complete" | "choice_made" | "time_elapsed" | "all_discoveries";
  config: Record<string, unknown>;
  once: boolean;
  action: TriggerAction;
}

export type TriggerAction =
  | { type: "narration"; text: string; duration: number }
  | { type: "cinematic"; cinematic_id: string }
  | { type: "unlock_scene"; target_scene: string }
  | { type: "spawn_npc"; npc_config: NPCInstance }
  | { type: "show_notification"; message: string; style?: string }
  | { type: "update_quest"; quest_text: string };

// ---- Cinematics ----

export interface CinematicSequence {
  id: string;
  camera_keyframes: {
    position: [number, number, number];
    look_at: [number, number, number];
    duration: number;
    easing?: string;
  }[];
  narration?: string;
  total_duration: number;
  on_complete?: TriggerAction;
}
