// ============================================
// Script — Stage 2 Output
// Generated by Scriptwriter Agent
// ============================================

export type Genre = "adventure" | "mystery" | "simulation" | "roleplay" | "documentary";

export type PedagogyMethod =
  | "worked_example"
  | "retrieval_practice"
  | "dual_coding"
  | "scaffolding"
  | "interleaving"
  | "elaborative_interrogation"
  | "spaced_repetition";

export interface Script {
  id: string;
  meta: ScriptMeta;
  characters: ScriptCharacter[];
  acts: Act[];
  alignment_report: AlignmentReport;
}

export interface ScriptMeta {
  title: string;
  subject: string;
  curriculum_ref: string;
  genre: Genre;
  target_duration_minutes: number;
  knowledge_graph_id: string;
  description: string;
}

export interface ScriptCharacter {
  id: string;
  name: string;
  role: string;
  personality: string;
  appearance: string;
  speech_style: string;
  knowledge_role: string; // what knowledge this NPC carries
  backstory?: string;
}

export interface Act {
  id: string;
  title: string;
  setting: ActSetting;
  scenes: Scene[];
}

export interface ActSetting {
  location: string;
  time_period: string;
  atmosphere: string;
  weather?: string;
}

export interface Scene {
  id: string;
  title: string;
  description: string;
  objective: string; // what the student should learn
  setting_override?: Partial<ActSetting>;
  npcs_present: string[]; // character IDs
  interactions: Interaction[];
  completion_condition: string;
  next_scene?: string;
  branches?: { condition: string; next_scene: string }[];
}

// ---- Interactions ----

export type InteractionType =
  | "dialogue"
  | "choice"
  | "explore"
  | "puzzle"
  | "observe"
  | "experiment";

export interface Interaction {
  id: string;
  type: InteractionType;
  description: string;

  // Pedagogy annotation (critical for evaluation!)
  pedagogy: {
    method: PedagogyMethod;
    rationale: string;
  };

  // Fact grounding (anti-hallucination!)
  grounded_facts: string[]; // Fact IDs from KnowledgeGraph
  factual_claims: FactualClaim[];

  // Type-specific content
  content: DialogueContent | ChoiceContent | ExploreContent | PuzzleContent | ObserveContent;
}

export interface FactualClaim {
  claim: string;
  source_fact_id: string;
  verification_status?: "verified" | "flagged" | "rejected";
}

// ---- Interaction Content Types ----

export interface DialogueContent {
  type: "dialogue";
  npc_id: string;
  trigger: "auto" | "proximity" | "click" | "after_interaction";
  trigger_ref?: string; // after which interaction
  initial_line: string;
  dialogue_points: string[]; // key points NPC should cover
  knowledge_to_convey: string[]; // Fact IDs
  allows_free_chat: boolean;
}

export interface ChoiceContent {
  type: "choice";
  prompt: string;
  options: ChoiceOption[];
  min_select?: number;
  max_select?: number;
  allow_retry: boolean;
}

export interface ChoiceOption {
  id: string;
  label: string;
  correct: boolean;
  feedback: string;
  consequence?: string;
  next_interaction?: string;
}

export interface ExploreContent {
  type: "explore";
  area_description: string;
  discoverable_items: DiscoverableItem[];
  time_limit?: number; // seconds, optional
}

export interface DiscoverableItem {
  id: string;
  name: string;
  description: string;
  location_hint: string;
  knowledge_revealed: string; // what the student learns
  linked_facts: string[];
}

export interface PuzzleContent {
  type: "puzzle";
  puzzle_description: string;
  puzzle_type: "matching" | "ordering" | "riddle" | "assembly" | "deduction";
  elements: { id: string; label: string; data?: string }[];
  solution: string[];
  hints: string[];
  knowledge_tested: string[];
}

export interface ObserveContent {
  type: "observe";
  target_description: string;
  observation_prompts: string[];
  correct_observations: string[];
  visual_highlights: string[];
}

// ---- Alignment Report ----

export interface AlignmentReport {
  objective_coverage: Record<
    string,
    {
      interaction_count: number;
      scene_ids: string[];
      pedagogy_methods: PedagogyMethod[];
      coverage_quality: "strong" | "adequate" | "weak";
    }
  >;
  uncovered_objectives: string[];
  pedagogy_distribution: Record<PedagogyMethod, number>;
  total_facts_referenced: number;
  total_interactions: number;
  estimated_duration_minutes: number;
}
